function catchErrorHandel(req, res, next, error) {}

export { catchErrorHandel };

const CatchError = {
  catchErrorHandel,
};

console.log(CatchError);
export { CatchError };
