const CatchError = {
  catchErrorHandel: function catchErrorHandel(req, res, next, error) {},
};

export { CatchError };
